export const ALL_LANGUAGES = [
  {
    LanguageID: 6,
    LanguageName: "Deutsch",
    ShortName: "de",
    AppHelps: [],
    Contacts: [],
    FormLabels: [],
    Legals: [],
    PrivacyPolicies: [],
    UserHasLanguages: [],
  },
  {
    LanguageID: 1,
    LanguageName: "English",
    ShortName: "en",
    AppHelps: [],
    Contacts: [],
    FormLabels: [],
    Legals: [],
    PrivacyPolicies: [],
    UserHasLanguages: [],
  },
  {
    LanguageID: 5,
    LanguageName: "Español",
    ShortName: "es",
    AppHelps: [],
    Contacts: [],
    FormLabels: [],
    Legals: [],
    PrivacyPolicies: [],
    UserHasLanguages: [],
  },
  {
    LanguageID: 7,
    LanguageName: "Français",
    ShortName: "fr",
    AppHelps: [],
    Contacts: [],
    FormLabels: [],
    Legals: [],
    PrivacyPolicies: [],
    UserHasLanguages: [],
  },
  {
    LanguageID: 2,
    LanguageName: "Italiano",
    ShortName: "it",
    AppHelps: [],
    Contacts: [],
    FormLabels: [],
    Legals: [],
    PrivacyPolicies: [],
    UserHasLanguages: [],
  },
  {
    LanguageID: 3,
    LanguageName: "Nederlandsche",
    ShortName: "nl",
    AppHelps: [],
    Contacts: [],
    FormLabels: [],
    Legals: [],
    PrivacyPolicies: [],
    UserHasLanguages: [],
  },
  {
    LanguageID: 9,
    LanguageName: "Português",
    ShortName: "pt",
    AppHelps: [],
    Contacts: [],
    FormLabels: [],
    Legals: [],
    PrivacyPolicies: [],
    UserHasLanguages: [],
  },
];

export const AllFormLabels = [
  {
    FormID: 1,
    FormName: "Login",
    LanguageID: 1,
    Labels: {
      lbl_username: "Email",
      lbl_password: "Password",
      lbl_login: "Login",
      lbl_forget_password: "Forgotten password",
      msg_username: "Please enter email",
      msg_password: "Please enter password",
      msg_invaliduser: "Email or password not correct. Please retry",
      msg_userexist:
        "User exists but is deactivated. Please contact service@doctorhouse.app",
      msg_alreadylogin:
        "User is already logged on the system, contact service@doctorhouse.app",
      msg_verification:
        "User is not verified. A verification email has been sent to your registered email",
      msg_location:
        "Not able to fetch the location co-ordinates due to some network issue. Please try again",
      lbl_showpwd: "Show password",
      lbl_hidepwd: "Hide password",
      lbl_lets: "Lets",
      lbl_biometric: "Biometric",
      lbl_loginotp: "Login via OTP",
      lbl_dont_account: "You don't have an account?",
      lbl_selectone: "Select one",
      lbl_otp: "Please enter OTP",
      lbl_mobile: "Mobile",
      msg_mobile: "An OTP has been sent to your registered mobile",
      msg_email: "An OTP has been sent to your registered email",
    },
    Language: null,
  },
  {
    FormID: 2,
    FormName: "SignUp",
    LanguageID: 1,
    Labels: {
      lbl_profile: "Profile",
      lbl_first_name: "First name",
      lbl_last_name: "Last name",
      lbl_dob: "Date of birth",
      lbl_address: "Address",
      lbl_city: "City",
      lbl_state: "State",
      lbl_country: "Country",
      lbl_zip: "Zip",
      lbl_mobile: "Mobile number",
      lbl_email: "Email",
      lbl_password: "Password",
      lbl_language: "Language",
      lbl_doctor: "Are you a doctor or veterinary?",
      lbl_otherinfo: "Other Information",
      lbl_medical_registration_number: "Medical registration number",
      lbl_speciality: "Speciality",
      lbl_signup: "Signup",
      lbl_update: "Update",
      lbl_pricefrom: "Price from",
      lbl_priceto: "Price to",
      msg_pricefrom: "Please enter price from",
      msg_priceto: "Please enter price to",
      msg_firstname: "Please enter first name",
      msg_lastname: "Please enter last name",
      msg_dob: "Please enter date of birth",
      msg_mobile: "Please enter mobile number",
      msg_email: "Please enter valid email address",
      msg_password: "Please enter password",
      msg_language: "Please enter language",
      msg_regnumber: "Please enter medical registration number",
      msg_speciality: "Please enter speciality",
      msg_aftersignup:
        "You are successfully registered on doctorhouse. A verification link has been sent to your email to confirm the registration.",
      msg_add_profile: "Please add your profile image",
      msg_add_document: "Please add your physician license",
      lbl_policy1: "Privacy notice on the processing of personal data",
      lbl_policy2: "Privacy policy",
      lbl_policy3: "document accessible via the following link",
      lbl_legal1:
        "Agreement to the processing of my data for marketing purposes",
      lbl_legal2: "News and personalized offers",
      lbl_legal3: "document accessible via the following link",
      msg_user_updated: "Profile updated successfully",
      msg_policy: "Please check the privacy policy. It is mandatory",
      lbl_country_code: "Select country code",
      msg_country_code: "Please select country code",
      lbl_code: "Country code",
      msg_userexist: "User already exist",
      lbl_default_language: "Language selected in login",
      lbl_docprofile: "Physician profile",
      lbl_profile1:
        "Agreement to the processing of my data for profiling purposes",
      lbl_profile2: "Profiling",
      lbl_profile3: "document accessible via the following link",
      lbl_eula1: "EULA - End User License Agreement",
      lbl_eula2: "EULA",
      lbl_eula3: "document accessible via the following link",
    },
    Language: null,
  },
  {
    FormID: 3,
    FormName: "ForgetPassword",
    LanguageID: 1,
    Labels: {
      lbl_enter_email: "Enter your email to recover your password",
      lbl_email: "Email",
      lbl_send: "Send",
      msg_wrongemail:
        "Entered email is not associated with a user. Please enter the right email",
      msg_resetpwd_link: "A reset password link has been sent to your email",
      lbl_web1: "Enter password other than older password",
      web_msg1: "Link not correct. Please use a valid link",
      web_msg2: "Password has been changed successfully",
      web_msg3:
        "This password is already taken please enter the new password again",
      web_msg4: "Password cannot be blank",
    },
    Language: null,
  },
  {
    FormID: 4,
    FormName: "Menu",
    LanguageID: 1,
    Labels: {
      lbl_profile: "Profile",
      lbl_payment: "Payment",
      lbl_privacy: "Privacy policy",
      lbl_legal: "News and personalized offers",
      lbl_contacts: "Contacts",
      lbl_settings: "Settings",
      lbl_help: "Help",
      lbl_logout: "Logout",
      lbl_eula: "EULA",
      lbl_profilo: "Profiling",
    },
    Language: null,
  },
  {
    FormID: 5,
    FormName: "Map_Patient",
    LanguageID: 1,
    Labels: {
      lbl_map_patient_search_res_1: "Dear #user",
      lbl_map_patient_search_res_2: "#no physicians found in your area",
      lbl_map_patient_search_res_3:
        "Click on physicians’ icon to view more information",
      lbl_map_patient_search_res_4: "No physician found in this area",
      lbl_free_version: "It is a free version",
      lbl_getdoctordetail: "Please subscribe to view the physicians’ detail",
    },
    Language: null,
  },
  {
    FormID: 6,
    FormName: "Map_Doctor",
    LanguageID: 1,
    Labels: {
      lbl_map_doctor_search_res_1: "Hello #user",
      lbl_map_doctor_search_res_2: "You are available for service",
      lbl_map_doctor_search_res_3: "You are not available for service",
      lbl_available: "Available",
      lbl_unavailable: "Not available",
      lbl_update: "Update",
    },
    Language: null,
  },
  {
    FormID: 7,
    FormName: "Map_Contact",
    LanguageID: 1,
    Labels: {
      lbl_contact_detail: "Contact details",
      lbl_otherinfo: "Other information",
      lbl_coupon_info: "Convention",
    },
    Language: null,
  },
  {
    FormID: 8,
    FormName: "Payment_History",
    LanguageID: 1,
    Labels: {
      lbl_start_date: "Start date",
      lbl_end_date: "End date",
      lbl_payment_history: "Payment history",
      lbl_active_plan: "Current active plan",
      lbl_pmt_year: "for a year (Welfare)",
      lbl_pmt_year_insurance: "for a year (Insurance)",
      lbl_pmt_day: "for a day",
      lbl_pmt_subscribe: "Subscribe",
      lbl_day: "Day",
      lbl_active: "Active",
      lbl_deactive: "Non active",
      lbl_pmt_subscribe_creditcard: "Subscribe with credit card",
      lbl_pmt_subscribe_coupon: "Subscribe with a voucher",
    },
    Language: null,
  },
  {
    FormID: 9,
    FormName: "Common",
    LanguageID: 1,
    Labels: {
      lbl_success: "Success",
      lbl_no_connection: "No connection available, please try later",
      lbl_submit: "Submit",
      lbl_choose_language: "Choose language",
      lbl_choose_radius: "Choose radius",
      lbl_choose_country: "Choose country",
      lbl_choose_specialization: "Choose specialization",
      lbl_all: "All",
      lbl_ok: "Ok",
      lbl_cancel: "Cancel",
      lbl_yes: "Yes",
      lbl_no: "No",
      lbl_resend: "Resend",
    },
    Language: null,
  },
  {
    FormID: 71,
    FormName: "Registration",
    LanguageID: 1,
    Labels: {
      lbl_subject: "Verification email",
      lbl_msg1: "Dear #user<br/><br/>",
      lbl_msg2:
        "Please click #link1 the link</a> to confirm your account<br/><br/>",
      lbl_msg3: "Thanks for using doctorhouse<br/><br/>",
      lbl_msg4: "Regards<br/>",
      lbl_msg5: "doctorhouse team",
    },
    Language: null,
  },
  {
    FormID: 77,
    FormName: "ResetPassword",
    LanguageID: 1,
    Labels: {
      lbl_subject: "Reset password",
      lbl_msg1: "Dear #user <br/><br/>",
      lbl_msg2: "Please click #link1 to reset</a> your password<br/><br/>",
      lbl_msg3: "Thanks for using doctorhouse<br/><br/>",
      lbl_msg4: "Regards<br/>",
      lbl_msg5: "doctorhouse team",
    },
    Language: null,
  },
  {
    FormID: 84,
    FormName: "Payments",
    LanguageID: 1,
    Labels: {
      lbl_total_subval: "Total subscription value",
      btn_paypal: "Pay by PayPal",
      lbl_creditcard: "credit card",
      lbl_monthyear: "MM/YY",
      lbl_cvv: "CVV",
      btn_creditcard: "Pay by credit card",
      lbl_couponcode: "Pay by voucher",
      msg_invalidcoupon: "Invalid voucher",
      msg_payment_error: "Error in payment try again",
      msg_credit_card: "Please enter card number",
      msg_cvv: "Please enter card CVV",
      msg_exp_date: "Please enter card expiration date",
      msg_coupon_code: "Please enter voucher",
      msg_invalid_cc: "Please enter correct credit card details",
      lbl_coupon_code: "Voucher",
    },
    Language: null,
  },
  {
    FormID: 115,
    FormName: "Reciept",
    LanguageID: 1,
    Labels: {
      lbl_reciept: "Receipt",
      lbl_milan: "Milan, Italy",
      lbl_subscriptiontype: "Subscription type",
      lbl_paymentdate: "Payment date",
      lbl_startdate: "Start date",
      lbl_enddate: "End date",
      lbl_total: "Total",
      lbl_issuedby: "Issued by",
      lbl_subscriptionvalueCC: "Credit card",
      lbl_subscriptionvalue_coupon: "Voucher",
      lbl_subscriptionvalue_paypal: "PayPal",
      lbl_esente: "VAT Exempt Article 10 No. 14 DPR 633/72",
    },
    Language: null,
  },
  {
    FormID: 122,
    FormName: "RecieptMail",
    LanguageID: 1,
    Labels: {
      lbl_subject: "Receipt doctorhouse #RNO",
      lbl_body:
        "Dear #User# <br/><br/>Thanks for using doctorhouse<br/><br/>Regards doctorhouse team",
    },
    Language: null,
  },
  {
    FormID: 129,
    FormName: "Phone_Verification",
    LanguageID: 1,
    Labels: {
      msg: "doctorhouse: OTP is #code and it will expire in 5 minutes",
    },
    Language: null,
  },
  {
    FormID: 136,
    FormName: "Web_Verification_Message",
    LanguageID: 1,
    Labels: {
      msg1: "Thanks, your email has been verified",
      msg2: "Enter the OTP sent on your phone to verify phone",
      msg3: "Your email is not verified",
      msg4: "Your mobile is not verified",
      msg5: "Your mobile is verified",
    },
    Language: null,
  },
  {
    FormID: 143,
    FormName: "Resend_Sms",
    LanguageID: 1,
    Labels: {
      msg1: "The OTP has been sent to your registered mobile number",
      msgPH: "OTP",
    },
    Language: null,
  },
  {
    FormID: 150,
    FormName: "Review",
    LanguageID: 1,
    Labels: {
      lbl_first: "Did you get physician answer to your request?",
      lbl_second: "Did the physician came to your house?",
      lbl_third: "Was the physician on time?",
      lbl_fourth: "Did the physician behave professionally?",
      lbl_fifth: "Was the rate agreed?",
      lbl_review: "Review",
      lbl_confirm: "Confirm",
      lbl_cancel: "Cancel",
      msg_confirm: "Please confirm",
      msg_cancel: "Are you sure you want to cancel",
      btn_insert_review: "Insert a review (max 500 chars)",
      msg_review_add: "Review added successfully",
      lbl_change_date: "Change date",
    },
    Language: null,
  },
  {
    FormID: 157,
    FormName: "Camera",
    LanguageID: 1,
    Labels: {
      lbl_option: "Select an option for image",
      lbl_camera: "Camera",
      lbl_gallery: "Gallery",
      lbl_close: "Close",
    },
    Language: null,
  },
  {
    FormID: 171,
    FormName: "Referrer",
    LanguageID: 1,
    Labels: {
      lbl_scanqr: "Scan QR",
      lbl_referrer: "Do you want to submit the referrer?",
      btn_yes: "Yes",
      btn_no: "No",
      msg_invalid_auth: "Invalid code",
      msg_invalid_email: "Invalid email code",
      msg_adding_referrer: "Error in adding referrer",
      msg_referrer_successfully: "Referrer added successfully",
    },
    Language: null,
  },
  {
    FormID: 258,
    FormName: "EmailOTP",
    LanguageID: 1,
    Labels: {
      lbl_subject: "email OTP",
      lbl_msg1: "Dear #user <br/><br/>",
      lbl_msg2: "The OTP for login is #otp<br/>",
      lbl_msg3: "Thanks for using doctorhouse<br/><br/>",
      lbl_msg4: "Regards<br/>",
      lbl_msg5: "doctorhouse team",
    },
    Language: null,
  },
  {
    FormID: 265,
    FormName: "OTPMessage",
    LanguageID: 1,
    Labels: {
      phoneotp: "The OTP has been sent to your registered mobile",
      emailotp: "The OTP has been sent to your registered email",
    },
    Language: null,
  },
  {
    FormID: 272,
    FormName: "Settings",
    LanguageID: 1,
    Labels: {
      lbl_theme: "Change to dark theme",
      lbl_biometric: "Biometric & screen locks",
    },
    Language: null,
  },
];
